layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: prithvikannan
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning
    web_url: https://github.com/topics/css
    image_url: https://static.thenounproject.com/png/2010152-200.png

  - name: IoT
    image_url: https://cdn2.iconfinder.com/data/icons/5g-internet/512/5g-internet-wifi-technology-16-512.png

  - name: Web Development
    web_url: https://github.com/topics/sass
    image_url: https://www.pngfind.com/pngs/m/415-4152510_web-development-icon-png-clipart-website-development-programming.png